# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rpc.compiled.command_pb2 as command__pb2


class CommandToolStub(object):
    """服务入口
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CommitIndexGil = channel.unary_unary(
                '/tools.CommandTool/CommitIndexGil',
                request_serializer=command__pb2.Request.SerializeToString,
                response_deserializer=command__pb2.Response.FromString,
                )
        self.CommitFund = channel.unary_unary(
                '/tools.CommandTool/CommitFund',
                request_serializer=command__pb2.Request.SerializeToString,
                response_deserializer=command__pb2.Response.FromString,
                )


class CommandToolServicer(object):
    """服务入口
    """

    def CommitIndexGil(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitFund(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandToolServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CommitIndexGil': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitIndexGil,
                    request_deserializer=command__pb2.Request.FromString,
                    response_serializer=command__pb2.Response.SerializeToString,
            ),
            'CommitFund': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitFund,
                    request_deserializer=command__pb2.Request.FromString,
                    response_serializer=command__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tools.CommandTool', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommandTool(object):
    """服务入口
    """

    @staticmethod
    def CommitIndexGil(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tools.CommandTool/CommitIndexGil',
            command__pb2.Request.SerializeToString,
            command__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommitFund(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tools.CommandTool/CommitFund',
            command__pb2.Request.SerializeToString,
            command__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
