# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rpc.services.classify_pb2 as classify__pb2


class ScreenRpcServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FundCategory = channel.unary_unary(
                '/services.ScreenRpcServer/FundCategory',
                request_serializer=classify__pb2.ClassifyReq.SerializeToString,
                response_deserializer=classify__pb2.ClassifyResp.FromString,
                )


class ScreenRpcServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FundCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScreenRpcServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FundCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.FundCategory,
                    request_deserializer=classify__pb2.ClassifyReq.FromString,
                    response_serializer=classify__pb2.ClassifyResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.ScreenRpcServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ScreenRpcServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FundCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/services.ScreenRpcServer/FundCategory',
            classify__pb2.ClassifyReq.SerializeToString,
            classify__pb2.ClassifyResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
