# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='basic.proto',
  package='services',
  syntax='proto3',
  serialized_options=b'Z\n.;services',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x62\x61sic.proto\x12\x08services\"2\n\tBasicInfo\x12\x10\n\x08secucode\x18\x01 \x01(\t\x12\x13\n\x0blaunch_date\x18\x02 \x01(\t\"\x16\n\x14\x46undBasicInfoRequest\":\n\x15\x46undBasicInfoResponse\x12!\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x13.services.BasicInfo\"\x1e\n\rFundsResponse\x12\r\n\x05\x66unds\x18\x01 \x03(\tB\x0cZ\n.;servicesb\x06proto3'
)




_BASICINFO = _descriptor.Descriptor(
  name='BasicInfo',
  full_name='services.BasicInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='secucode', full_name='services.BasicInfo.secucode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='launch_date', full_name='services.BasicInfo.launch_date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=75,
)


_FUNDBASICINFOREQUEST = _descriptor.Descriptor(
  name='FundBasicInfoRequest',
  full_name='services.FundBasicInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=99,
)


_FUNDBASICINFORESPONSE = _descriptor.Descriptor(
  name='FundBasicInfoResponse',
  full_name='services.FundBasicInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='services.FundBasicInfoResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=159,
)


_FUNDSRESPONSE = _descriptor.Descriptor(
  name='FundsResponse',
  full_name='services.FundsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='funds', full_name='services.FundsResponse.funds', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=191,
)

_FUNDBASICINFORESPONSE.fields_by_name['data'].message_type = _BASICINFO
DESCRIPTOR.message_types_by_name['BasicInfo'] = _BASICINFO
DESCRIPTOR.message_types_by_name['FundBasicInfoRequest'] = _FUNDBASICINFOREQUEST
DESCRIPTOR.message_types_by_name['FundBasicInfoResponse'] = _FUNDBASICINFORESPONSE
DESCRIPTOR.message_types_by_name['FundsResponse'] = _FUNDSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BasicInfo = _reflection.GeneratedProtocolMessageType('BasicInfo', (_message.Message,), {
  'DESCRIPTOR' : _BASICINFO,
  '__module__' : 'basic_pb2'
  # @@protoc_insertion_point(class_scope:services.BasicInfo)
  })
_sym_db.RegisterMessage(BasicInfo)

FundBasicInfoRequest = _reflection.GeneratedProtocolMessageType('FundBasicInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _FUNDBASICINFOREQUEST,
  '__module__' : 'basic_pb2'
  # @@protoc_insertion_point(class_scope:services.FundBasicInfoRequest)
  })
_sym_db.RegisterMessage(FundBasicInfoRequest)

FundBasicInfoResponse = _reflection.GeneratedProtocolMessageType('FundBasicInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _FUNDBASICINFORESPONSE,
  '__module__' : 'basic_pb2'
  # @@protoc_insertion_point(class_scope:services.FundBasicInfoResponse)
  })
_sym_db.RegisterMessage(FundBasicInfoResponse)

FundsResponse = _reflection.GeneratedProtocolMessageType('FundsResponse', (_message.Message,), {
  'DESCRIPTOR' : _FUNDSRESPONSE,
  '__module__' : 'basic_pb2'
  # @@protoc_insertion_point(class_scope:services.FundsResponse)
  })
_sym_db.RegisterMessage(FundsResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
