# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: funds.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)
_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='funds.proto',
  package='rpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x66unds.proto\x12\x03rpc\"1\n\x13\x46undCategoryRequest\x12\x0c\n\x04\x66und\x18\x01 \x03(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\"L\n\x14\x46undCategoryResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x03\x12\x1f\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x11.rpc.FundCategory\"2\n\x0c\x46undCategory\x12\x10\n\x08secucode\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\tb\x06proto3'
)




_FUNDCATEGORYREQUEST = _descriptor.Descriptor(
  name='FundCategoryRequest',
  full_name='rpc.FundCategoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fund', full_name='rpc.FundCategoryRequest.fund', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kind', full_name='rpc.FundCategoryRequest.kind', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=69,
)


_FUNDCATEGORYRESPONSE = _descriptor.Descriptor(
  name='FundCategoryResponse',
  full_name='rpc.FundCategoryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='rpc.FundCategoryResponse.status_code', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='rpc.FundCategoryResponse.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=147,
)


_FUNDCATEGORY = _descriptor.Descriptor(
  name='FundCategory',
  full_name='rpc.FundCategory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='secucode', full_name='rpc.FundCategory.secucode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='category', full_name='rpc.FundCategory.category', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=199,
)

_FUNDCATEGORYRESPONSE.fields_by_name['data'].message_type = _FUNDCATEGORY
DESCRIPTOR.message_types_by_name['FundCategoryRequest'] = _FUNDCATEGORYREQUEST
DESCRIPTOR.message_types_by_name['FundCategoryResponse'] = _FUNDCATEGORYRESPONSE
DESCRIPTOR.message_types_by_name['FundCategory'] = _FUNDCATEGORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FundCategoryRequest = _reflection.GeneratedProtocolMessageType('FundCategoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _FUNDCATEGORYREQUEST,
  '__module__' : 'funds_pb2'
  # @@protoc_insertion_point(class_scope:rpc.FundCategoryRequest)
  })
_sym_db.RegisterMessage(FundCategoryRequest)

FundCategoryResponse = _reflection.GeneratedProtocolMessageType('FundCategoryResponse', (_message.Message,), {
  'DESCRIPTOR' : _FUNDCATEGORYRESPONSE,
  '__module__' : 'funds_pb2'
  # @@protoc_insertion_point(class_scope:rpc.FundCategoryResponse)
  })
_sym_db.RegisterMessage(FundCategoryResponse)

FundCategory = _reflection.GeneratedProtocolMessageType('FundCategory', (_message.Message,), {
  'DESCRIPTOR' : _FUNDCATEGORY,
  '__module__' : 'funds_pb2'
  # @@protoc_insertion_point(class_scope:rpc.FundCategory)
  })
_sym_db.RegisterMessage(FundCategory)


# @@protoc_insertion_point(module_scope)
