# Generated by Django 3.1 on 2020-09-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='问题ID')),
                ('text', models.TextField(verbose_name='问题描述')),
                ('date', models.DateTimeField(verbose_name='问题发布日期')),
            ],
            options={
                'verbose_name': '问题列表',
                'verbose_name_plural': '问题列表',
                'db_table': 'questionnaire_questions',
            },
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.IntegerField(verbose_name='选项ID')),
                ('text', models.TextField(verbose_name='选项描述')),
                ('point', models.IntegerField(verbose_name='选项得分')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questions')),
            ],
            options={
                'verbose_name': '选项列表',
                'verbose_name_plural': '选项列表',
                'db_table': 'questionnaire_choices',
                'unique_together': {('question_id', 'choice_id')},
            },
        ),
    ]
