# Generated by Django 3.1 on 2020-09-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='subject',
            field=models.CharField(max_length=30, null=True, verbose_name='主题'),
        ),
    ]
