# Generated by Django 3.1 on 2020-09-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_client_result_resultinfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultinfo',
            unique_together={('client', 'date')},
        ),
    ]
