# Generated by Django 3.1 on 2020-09-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20200915_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='associate_nme',
            new_name='associate_name',
        ),
    ]
