# Generated by Django 3.1.5 on 2021-01-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20210128_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='客户账号'),
        ),
        migrations.AlterField(
            model_name='client',
            name='associate_account',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='关联账号'),
        ),
        migrations.AlterField(
            model_name='client',
            name='associate_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='关联账户名称'),
        ),
    ]
