# Generated by Django 3.1.5 on 2021-01-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20210128_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account',
            field=models.CharField(max_length=30, unique=True, verbose_name='客户账号'),
        ),
    ]
