
# database configs
database:
  host: 10.170.129.129
  port: 3306
  username: fof
  password: 123456
  database: am_sma_second

# file path
target_path: "data"

# targets
targets:
  sma_portfolio: '组合信息表'
  sma_balance: '组合资产负债表'
  sma_balance_expanded: '组合应收应付表'
  sma_income_portfolio: '组合损益表'
  sma_income_asset: '资产损益表'
  sma_holding_fund: '组合持仓表'
  sma_transactions: '组合流水表'
  sma_detail_fee: '组合费用表'
  sma_evaluate_benchmark: '基准净值表'
  sma_fund_style: '基金风格表'
  sma_interest_tax: '基金应付利息税'
