# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from services import backtest_pb2 as backtest__pb2


class BacktestServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StandardPortfolioNav = channel.unary_unary(
                '/services.BacktestServer/StandardPortfolioNav',
                request_serializer=backtest__pb2.BRequest.NullRequest.SerializeToString,
                response_deserializer=backtest__pb2.BResponse.NavResponse.FromString,
                )
        self.Weight = channel.unary_unary(
                '/services.BacktestServer/Weight',
                request_serializer=backtest__pb2.BRequest.NullRequest.SerializeToString,
                response_deserializer=backtest__pb2.BResponse.WeightResponse.FromString,
                )
        self.IndexPortfolioNav = channel.unary_unary(
                '/services.BacktestServer/IndexPortfolioNav',
                request_serializer=backtest__pb2.BRequest.NullRequest.SerializeToString,
                response_deserializer=backtest__pb2.BResponse.NavResponse.FromString,
                )
        self.FundIndexPortfolioNav = channel.unary_unary(
                '/services.BacktestServer/FundIndexPortfolioNav',
                request_serializer=backtest__pb2.BRequest.NullRequest.SerializeToString,
                response_deserializer=backtest__pb2.BResponse.NavResponse.FromString,
                )
        self.SyncData = channel.unary_unary(
                '/services.BacktestServer/SyncData',
                request_serializer=backtest__pb2.BRequest.NullRequest.SerializeToString,
                response_deserializer=backtest__pb2.BResponse.StatusResponse.FromString,
                )


class BacktestServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StandardPortfolioNav(self, request, context):
        """标准组合回测净值
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Weight(self, request, context):
        """MVO优化后资产配置比例
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IndexPortfolioNav(self, request, context):
        """宽基指数组合回测净值
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FundIndexPortfolioNav(self, request, context):
        """基金指数组合回测净值
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncData(self, request, context):
        """同步数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BacktestServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StandardPortfolioNav': grpc.unary_unary_rpc_method_handler(
                    servicer.StandardPortfolioNav,
                    request_deserializer=backtest__pb2.BRequest.NullRequest.FromString,
                    response_serializer=backtest__pb2.BResponse.NavResponse.SerializeToString,
            ),
            'Weight': grpc.unary_unary_rpc_method_handler(
                    servicer.Weight,
                    request_deserializer=backtest__pb2.BRequest.NullRequest.FromString,
                    response_serializer=backtest__pb2.BResponse.WeightResponse.SerializeToString,
            ),
            'IndexPortfolioNav': grpc.unary_unary_rpc_method_handler(
                    servicer.IndexPortfolioNav,
                    request_deserializer=backtest__pb2.BRequest.NullRequest.FromString,
                    response_serializer=backtest__pb2.BResponse.NavResponse.SerializeToString,
            ),
            'FundIndexPortfolioNav': grpc.unary_unary_rpc_method_handler(
                    servicer.FundIndexPortfolioNav,
                    request_deserializer=backtest__pb2.BRequest.NullRequest.FromString,
                    response_serializer=backtest__pb2.BResponse.NavResponse.SerializeToString,
            ),
            'SyncData': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncData,
                    request_deserializer=backtest__pb2.BRequest.NullRequest.FromString,
                    response_serializer=backtest__pb2.BResponse.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.BacktestServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BacktestServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StandardPortfolioNav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/services.BacktestServer/StandardPortfolioNav',
            backtest__pb2.BRequest.NullRequest.SerializeToString,
            backtest__pb2.BResponse.NavResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Weight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/services.BacktestServer/Weight',
            backtest__pb2.BRequest.NullRequest.SerializeToString,
            backtest__pb2.BResponse.WeightResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IndexPortfolioNav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/services.BacktestServer/IndexPortfolioNav',
            backtest__pb2.BRequest.NullRequest.SerializeToString,
            backtest__pb2.BResponse.NavResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FundIndexPortfolioNav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/services.BacktestServer/FundIndexPortfolioNav',
            backtest__pb2.BRequest.NullRequest.SerializeToString,
            backtest__pb2.BResponse.NavResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/services.BacktestServer/SyncData',
            backtest__pb2.BRequest.NullRequest.SerializeToString,
            backtest__pb2.BResponse.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
