# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sync_pb2 as sync__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='services.proto',
  package='services',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eservices.proto\x12\x08services\x1a\nsync.proto2\xa7\x01\n\x06Server\x12\x35\n\x04Ping\x12\x15.services.PingRequest\x1a\x16.services.PingResponse\x12\x30\n\x07SyncAll\x12\x11.services.Request\x1a\x12.services.Response\x12\x34\n\x0bSyncPrimary\x12\x11.services.Request\x1a\x12.services.Responseb\x06proto3'
  ,
  dependencies=[sync__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='services.Server',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=41,
  serialized_end=208,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='services.Server.Ping',
    index=0,
    containing_service=None,
    input_type=sync__pb2._PINGREQUEST,
    output_type=sync__pb2._PINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SyncAll',
    full_name='services.Server.SyncAll',
    index=1,
    containing_service=None,
    input_type=sync__pb2._REQUEST,
    output_type=sync__pb2._RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SyncPrimary',
    full_name='services.Server.SyncPrimary',
    index=2,
    containing_service=None,
    input_type=sync__pb2._REQUEST,
    output_type=sync__pb2._RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
