# Generated by Django 3.1 on 2020-09-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secucode', models.CharField(max_length=30, unique=True, verbose_name='指数代码')),
            ],
            options={
                'verbose_name': '指数列表',
                'verbose_name_plural': '指数列表',
                'db_table': 'sma_index',
            },
        ),
        migrations.CreateModel(
            name='IndexQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_close', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='昨收')),
                ('close', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='收盘价')),
                ('change', models.DecimalField(decimal_places=8, max_digits=19, verbose_name='涨跌幅')),
                ('date', models.DateField(verbose_name='交易日')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.index', to_field='secucode')),
            ],
            options={
                'verbose_name': '指数行情',
                'verbose_name_plural': '指数行情',
                'db_table': 'sma_index_quote',
            },
        ),
        migrations.CreateModel(
            name='IndexBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuabbr', models.CharField(max_length=100, verbose_name='证券简称')),
                ('chiname', models.CharField(max_length=100, verbose_name='中文名称')),
                ('category', models.CharField(max_length=100, verbose_name='指数类别')),
                ('source', models.IntegerField(choices=[(1, '聚源'), (2, '万得')], default=1, verbose_name='数据来源')),
                ('basedate', models.DateTimeField(verbose_name='基日')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.index', to_field='secucode')),
            ],
            options={
                'verbose_name': '指数基础信息',
                'verbose_name_plural': '指数基础信息',
                'db_table': 'sma_index_basic',
            },
        ),
    ]
