# Generated by Django 4.0.1 on 2022-02-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_valuation_valuationex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationBenchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_nav', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='单位净值')),
                ('date', models.DateField(verbose_name='交易日')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '5.4 组合基准估值表',
                'verbose_name_plural': '5.4 组合基准估值表',
                'db_table': 'sma_balance_benchmark',
                'get_latest_by': 'date',
                'index_together': {('port_code', 'date')},
            },
        ),
    ]
