# Generated by Django 3.1 on 2020-09-08 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_auto_20200904_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='组合ID')),
                ('port_code', models.CharField(max_length=12, unique=True, verbose_name='组合代码')),
                ('port_name', models.CharField(max_length=20, verbose_name='组合名称')),
                ('manager', models.CharField(max_length=20, verbose_name='管理人')),
                ('init_money', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='初始资金')),
                ('purchase_fee', models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='申购费')),
                ('redemption_fee', models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='赎回费')),
                ('base', models.CharField(max_length=100, verbose_name='业绩比较基准')),
                ('describe', models.CharField(max_length=100, verbose_name='组合描述')),
                ('launch_date', models.DateTimeField(verbose_name='成立日期')),
            ],
            options={
                'verbose_name': '组合基础信息',
                'verbose_name_plural': '组合基础信息',
                'db_table': 'sma_portfolio',
            },
        ),
        migrations.CreateModel(
            name='IncomeAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_profit', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='基金整体收益')),
                ('equity', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='权益')),
                ('bond', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='固收')),
                ('alter', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='另类')),
                ('money', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='货币及现金')),
                ('date', models.DateField(verbose_name='日期')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '组合资产损益表',
                'verbose_name_plural': '组合资产损益表',
                'db_table': 'sma_income_asset',
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_nav', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='单位净值')),
                ('net_asset', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='资产净值')),
                ('change', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='涨跌')),
                ('change_pct', models.DecimalField(decimal_places=8, default=0, max_digits=12, verbose_name='涨跌幅')),
                ('date', models.DateField(verbose_name='日期')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '组合损益表',
                'verbose_name_plural': '组合损益表',
                'db_table': 'sma_income_portfolio',
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='BalanceExpanded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_rec', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='应收股利')),
                ('interest_rec', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='应收利息')),
                ('purchase_rec', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='应收申购款')),
                ('redemption_pay', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='应付赎回款')),
                ('redemption_fee_pay', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='应付赎回费')),
                ('management_pay', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='应付管理人报酬')),
                ('custodian_pay', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='应付托管费')),
                ('withholding_pay', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='预提费用')),
                ('date', models.DateField(verbose_name='日期')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investment.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '组合应收应付表',
                'verbose_name_plural': '组合应收应付表',
                'db_table': 'sma_balance_expanded',
                'get_latest_by': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='资产')),
                ('debt', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='负债')),
                ('net_asset', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='资产净值')),
                ('shares', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='份额')),
                ('unit_nav', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='单位净值')),
                ('acc_nav', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='累计单位净值')),
                ('savings', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='银行存款')),
                ('fund_invest', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='基金投资')),
                ('liquidation', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='证券清算款')),
                ('value_added', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='估值增值')),
                ('profit_pay', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='应付利润(红利)')),
                ('date', models.DateField(verbose_name='日期')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investment.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '组合资产负债',
                'verbose_name_plural': '组合资产负债',
                'db_table': 'sma_balance',
                'get_latest_by': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secucode', models.CharField(blank=True, max_length=12, null=True, verbose_name='证券代码')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='发生金额')),
                ('balance', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='发生后余额')),
                ('order_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='委托价格')),
                ('order_value', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='委托数量')),
                ('deal_value', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='发生数量')),
                ('fee', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='费用')),
                ('operation_amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='科目发生额')),
                ('operation', models.CharField(max_length=30, verbose_name='业务类型')),
                ('subject_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='科目名称')),
                ('date', models.DateField(verbose_name='交易发生时间')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '组合交易流水',
                'verbose_name_plural': '组合交易流水',
                'db_table': 'sma_transactions',
                'get_latest_by': ['date'],
                'index_together': {('port_code', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secucode', models.CharField(max_length=12, verbose_name='证券代码')),
                ('holding_value', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='持仓数量')),
                ('mkt_cap', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='市值')),
                ('current_cost', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='持仓成本')),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='含费用成本')),
                ('fee', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='费用合计')),
                ('flow_profit', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='浮动盈亏')),
                ('total_profit', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='总盈亏')),
                ('dividend', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='当日分红')),
                ('total_dividend', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='累计分红')),
                ('date', models.DateField(verbose_name='交易日')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '组合持基明细',
                'verbose_name_plural': '组合持基明细',
                'db_table': 'sma_holding_fund',
                'get_latest_by': 'date',
                'index_together': {('port_code', 'date')},
            },
        ),
    ]
