# Generated by Django 4.0.1 on 2022-02-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_valuationbenchmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secucode', models.CharField(max_length=50, unique=True, verbose_name='证券代码')),
                ('secuabbr', models.CharField(max_length=250, verbose_name='证券名称')),
                ('category', models.CharField(max_length=50, verbose_name='证券类型')),
                ('category_code', models.CharField(max_length=20, verbose_name='类型代码')),
            ],
            options={
                'verbose_name': '3.1 证券主表-估值表',
                'verbose_name_plural': '3.1 证券主表-估值表',
                'db_table': 'sma_security',
            },
        ),
        migrations.CreateModel(
            name='SecurityQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='单位净值')),
                ('note', models.CharField(max_length=250, null=True, verbose_name='行情备注')),
                ('date', models.DateField(verbose_name='行情日期')),
                ('auto_date', models.DateField(verbose_name='生成日期')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code', verbose_name='组合代码')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.security', to_field='secucode', verbose_name='证券代码')),
            ],
            options={
                'verbose_name': '3.2 证券行情-估值表',
                'verbose_name_plural': '3.2 证券行情-估值表',
                'db_table': 'sma_security_quote',
            },
        ),
        migrations.CreateModel(
            name='SecurityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(choices=[('权益类', '权益类'), ('固收类', '固收类'), ('另类', '另类'), ('货币', '货币')], max_length=20, verbose_name='一级分类')),
                ('second', models.CharField(blank=True, max_length=20, null=True, verbose_name='二级分类')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.security', to_field='secucode', verbose_name='证券代码')),
            ],
            options={
                'verbose_name': '3.3 证券分类表（自定义）',
                'verbose_name_plural': '3.3 证券分类表（自定义）',
                'db_table': 'sma_security_category',
            },
        ),
    ]
