# Generated by Django 3.1 on 2020-09-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_balance_balanceexpanded_holding_income_incomeasset_portfolio_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='管理费')),
                ('custodian', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='托管费')),
                ('audit', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='审计费')),
                ('date', models.DateField(verbose_name='业务日期')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '组合费用提取明细',
                'verbose_name_plural': '组合费用提取明细',
                'db_table': 'sma_detail_fee',
                'get_latest_by': 'date',
            },
        ),
    ]
