# Generated by Django 3.1.2 on 2020-11-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_detailfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='port_type',
            field=models.IntegerField(choices=[(1, '现金型'), (2, '固收型'), (3, '平衡型'), (4, '成长型'), (5, '权益型')], default=None),
            preserve_default=False,
        ),
    ]
