# Generated by Django 3.1.2 on 2020-11-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_portfolio_port_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='cash_dividend',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='分红'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_type',
            field=models.IntegerField(choices=[(1, '现金型'), (2, '固收型'), (3, '平衡型'), (4, '成长型'), (5, '权益型')], default=3, verbose_name='组合类型'),
        ),
    ]
