# Generated by Django 3.1.2 on 2020-11-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_auto_20201106_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='port_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code'),
        ),
        migrations.AlterField(
            model_name='balanceexpanded',
            name='port_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code'),
        ),
    ]
