# Generated by Django 3.1.2 on 2020-11-09 13:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_detailfee_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('secucode', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='基金代码')),
                ('secuname', models.CharField(max_length=50, verbose_name='基金简称')),
            ],
            options={
                'verbose_name': '基金主表',
                'verbose_name_plural': '基金主表',
                'db_table': 'sma_funds',
            },
        ),
        migrations.CreateModel(
            name='FundStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundstyle', models.CharField(max_length=20, verbose_name='基金投资风格')),
                ('fundtype', models.CharField(max_length=20, verbose_name='基金类型')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.funds')),
            ],
            options={
                'verbose_name': '5.3 基金风格',
                'verbose_name_plural': '5.3 基金风格',
                'db_table': 'sma_fund_style',
            },
        ),
        migrations.CreateModel(
            name='FundPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nv', models.DecimalField(decimal_places=4, max_digits=18, null=True, verbose_name='净资产值(元)')),
                ('nav', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='单位净值')),
                ('acc_nav', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='累计单位净值')),
                ('dailyprofit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='万份收益')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='交易日')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.funds')),
            ],
            options={
                'verbose_name': '基金累计净值表',
                'verbose_name_plural': '基金累计净值表',
                'db_table': 'sma_fund_price',
                'get_latest_by': ['date'],
                'index_together': {('secucode', 'date')},
            },
        ),
    ]
