# Generated by Django 3.1.2 on 2020-11-10 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0009_fundprice_funds_fundstyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationBenchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_nav', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='单位净值')),
                ('date', models.DateField(verbose_name='交易日')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '组合基准净值表',
                'verbose_name_plural': '组合基准净值表',
                'db_table': 'sma_evaluate_benchmark',
                'get_latest_by': 'date',
                'index_together': {('port_code', 'date')},
            },
        ),
    ]
