# Generated by Django 3.1.2 on 2020-11-11 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0010_valuationbenchmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAdjPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='单位净值')),
                ('adj_nav', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='累计单位净值')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='交易日')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.funds')),
            ],
            options={
                'verbose_name': '基金复权单位净值表',
                'verbose_name_plural': '基金复权单位净值表',
                'db_table': 'sma_fund_adj_price',
                'get_latest_by': ['date'],
                'index_together': {('secucode', 'date')},
            },
        ),
    ]
