# Generated by Django 3.1.2 on 2020-11-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_fundadjprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundstyle',
            options={'verbose_name': '基金风格', 'verbose_name_plural': '基金风格'},
        ),
        migrations.CreateModel(
            name='FundPurchaseAndRedeem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_type', models.CharField(max_length=20, null=True, verbose_name='申购状态')),
                ('redeem_type', models.CharField(max_length=20, null=True, verbose_name='赎回状态')),
                ('min_apply', models.CharField(max_length=20, null=True, verbose_name='购买起点')),
                ('max_apply', models.CharField(max_length=20, null=True, verbose_name='单日限额')),
                ('date', models.DateField(auto_now=True)),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.funds')),
            ],
            options={
                'verbose_name': '基金申赎状态',
                'verbose_name_plural': '基金申赎状态',
                'db_table': 'sma_fund_purchase_and_redeem',
            },
        ),
    ]
