# Generated by Django 3.1.2 on 2020-11-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0014_tradingdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('secucode', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='股票代码')),
                ('secuname', models.CharField(max_length=50, verbose_name='股票简称')),
            ],
            options={
                'verbose_name': '股票列表',
                'verbose_name_plural': '股票列表',
                'db_table': 'sma_stocks',
            },
        ),
        migrations.CreateModel(
            name='FundHoldingStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=1, verbose_name='排名')),
                ('ratio', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='占净值比')),
                ('date', models.DateField(verbose_name='报告期')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.funds', verbose_name='基金代码')),
                ('stockcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.stock', verbose_name='股票代码')),
            ],
            options={
                'verbose_name': '基金持股情况',
                'verbose_name_plural': '基金持股情况',
                'db_table': 'sma_fund_holding_stock',
            },
        ),
    ]
