# Generated by Django 3.1.2 on 2020-11-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0015_fundholdingstock_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundholdingstock',
            name='stockname',
            field=models.CharField(default=None, max_length=20, verbose_name='股票代码'),
            preserve_default=False,
        ),
    ]
