# Generated by Django 3.1.2 on 2020-11-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0016_fundholdingstock_stockname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundholdingstock',
            name='stockcode',
            field=models.CharField(max_length=20, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='fundholdingstock',
            name='stockname',
            field=models.CharField(max_length=20, verbose_name='股票简称'),
        ),
    ]
