# Generated by Django 3.1.2 on 2020-11-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0017_auto_20201112_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundholdingstock',
            name='ratio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='占净值比'),
        ),
    ]
