# Generated by Django 3.1.2 on 2020-11-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0018_auto_20201112_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('target_risk', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='目标风险')),
                ('annual_r', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='年化收益')),
                ('risk', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='年化波动')),
                ('sharpe', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='夏普比')),
                ('hs300', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='沪深300')),
                ('zcf', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='中债总财富')),
                ('qyz', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='中债企业债')),
                ('hb', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='货币基金')),
                ('zz500', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='中证500')),
                ('hj', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='上海金现')),
                ('zz', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='中证转债')),
                ('hs', models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='恒生指数')),
            ],
            options={
                'verbose_name': '回测用只指数权重',
                'verbose_name_plural': '回测用只指数权重',
                'db_table': 'sma_backtest_weight',
            },
        ),
    ]
