# Generated by Django 3.1.2 on 2020-11-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0019_assetweight'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='assetweight',
            index_together={('date', 'target_risk')},
        ),
    ]
