# Generated by Django 3.1.2 on 2020-11-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0020_auto_20201113_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetweight',
            options={'verbose_name': '回测用指数权重', 'verbose_name_plural': '回测用指数权重'},
        ),
        migrations.AddField(
            model_name='assetweight',
            name='equity_bound_limit',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='股指仓位上限'),
        ),
    ]
