# Generated by Django 3.1.2 on 2020-11-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0021_auto_20201113_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIndustrySW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstindustryname', models.CharField(max_length=10, verbose_name='一级分类')),
                ('secondindustryname', models.CharField(max_length=20, verbose_name='二级分类')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.stock', verbose_name='股票代码')),
            ],
            options={
                'verbose_name': '股票申万行业分类',
                'verbose_name_plural': '股票申万行业分类',
                'db_table': 'sma_stocks_industry_sw',
            },
        ),
    ]
