# Generated by Django 3.1.2 on 2020-11-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0022_stockindustrysw'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundPurchaseFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.IntegerField(default=0, verbose_name='区间下限(<x)')),
                ('high', models.IntegerField(null=True, verbose_name='区间上限(x<=)')),
                ('fee', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='费率')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.funds', verbose_name='基金代码')),
            ],
            options={
                'verbose_name': '基金申购费率(天天基金网)',
                'verbose_name_plural': '基金申购费率(天天基金网)',
                'db_table': 'sma_fund_purchase_fee',
            },
        ),
    ]
