# Generated by Django 3.1.2 on 2020-11-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0024_fundpurchasefee_operate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundpurchasefee',
            options={'verbose_name': '基金申购赎回费率(天天基金网)', 'verbose_name_plural': '基金申购赎回费率(天天基金网)'},
        ),
        migrations.AlterField(
            model_name='fundpurchasefee',
            name='operate',
            field=models.CharField(choices=[('buy', '买'), ('sell', '卖')], max_length=4, verbose_name='交易方向'),
        ),
        migrations.CreateModel(
            name='StockRealtimePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='实时价格')),
                ('date', models.DateField(verbose_name='日期')),
                ('time', models.TimeField(verbose_name='时间')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.stock', verbose_name='股票代码')),
            ],
            options={
                'verbose_name': '股票实时价格',
                'verbose_name_plural': '股票实时价格',
                'db_table': 'sma_stocks_realtime_price',
            },
        ),
    ]
