# Generated by Django 3.1.2 on 2020-11-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0025_auto_20201123_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrealtimeprice',
            name='prev_close',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='昨收'),
        ),
    ]
