# Generated by Django 3.1.2 on 2020-11-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0026_stockrealtimeprice_prev_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_value', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='小盘价值')),
                ('small_growth', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='小盘成长')),
                ('mid_value', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='中盘价值')),
                ('mid_growth', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='中盘成长')),
                ('large_value', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='大盘价值')),
                ('large_growth', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='大盘成长')),
                ('bond', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='债券')),
                ('r_square', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='R方')),
                ('date', models.DateField(verbose_name='日期')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code', verbose_name='组合代码')),
            ],
            options={
                'verbose_name': '组合风格',
                'verbose_name_plural': '组合风格',
                'db_table': 'sma_style',
            },
        ),
    ]
