# Generated by Django 3.1.2 on 2020-11-25 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0027_portfoliostyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAssociate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relate', models.CharField(max_length=10, verbose_name='关联基金代码')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.funds', verbose_name='基金代码')),
            ],
            options={
                'verbose_name': '基金代码关联',
                'verbose_name_plural': '基金代码关联',
                'db_table': 'sma_fund_associate',
            },
        ),
    ]
