# Generated by Django 3.1.2 on 2020-11-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0029_fundassetallocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='activation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='开户费'),
        ),
    ]
