# Generated by Django 3.1.2 on 2020-11-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0030_portfolio_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundholdingstock',
            name='publish',
            field=models.CharField(choices=[('年报', '年报'), ('季报', '季报')], default='季报', max_length=8, verbose_name='报告类型'),
        ),
    ]
