# Generated by Django 3.1.2 on 2020-11-30 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0031_fundholdingstock_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuabbr', models.CharField(max_length=20, verbose_name='基金简称')),
                ('date', models.DateTimeField(verbose_name='公告日期')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(null=True, verbose_name='公告内容')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.funds', verbose_name='基金代码')),
            ],
            options={
                'verbose_name': '基金公告',
                'verbose_name_plural': '基金公告',
                'db_table': 'sma_fund_announcement',
            },
        ),
    ]
