# Generated by Django 3.1.2 on 2020-12-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0032_fundannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('beta', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='贝塔')),
                ('momentum', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='动量')),
                ('size', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='市值')),
                ('earnyild', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='盈利')),
                ('resvol', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='波动')),
                ('growth', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='成长')),
                ('btop', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='质量')),
                ('leverage', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='杠杆')),
                ('liquidty', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='流动')),
                ('sizenl', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='非线性市值')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.stock', verbose_name='股票代码')),
            ],
            options={
                'verbose_name': '股票因子暴露',
                'verbose_name_plural': '股票因子暴露',
                'db_table': 'sma_stock_exposure',
                'index_together': {('secucode', 'date')},
            },
        ),
    ]
