# Generated by Django 3.1.2 on 2020-12-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0033_stockexpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexbasicinfo',
            name='secucode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.index', to_field='secucode', verbose_name='指数代码'),
        ),
        migrations.AlterField(
            model_name='indexquote',
            name='secucode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.index', to_field='secucode', verbose_name='指数代码'),
        ),
        migrations.CreateModel(
            name='IndexComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockcode', models.CharField(max_length=20, verbose_name='股票代码')),
                ('weight', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='权重')),
                ('date', models.DateField(verbose_name='日期')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.index', to_field='secucode', verbose_name='指数代码')),
            ],
            options={
                'verbose_name': '指数成分',
                'verbose_name_plural': '指数成分',
                'db_table': 'sma_index_component',
                'get_latest_by': 'date',
                'unique_together': {('secucode', 'date')},
            },
        ),
    ]
