# Generated by Django 3.1.2 on 2020-12-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0037_portfoliobrinson'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='有效'),
        ),
    ]
