# Generated by Django 3.1.2 on 2020-12-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0038_portfolio_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliobrinson',
            name='industry',
            field=models.CharField(default=None, max_length=20, verbose_name='行业'),
            preserve_default=False,
        ),
    ]
