# Generated by Django 3.1.2 on 2020-12-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0039_portfoliobrinson_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisorcode', models.IntegerField(verbose_name='管理人代码')),
                ('advisorname', models.CharField(max_length=50, verbose_name='管理人名称')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.funds', verbose_name='基金代码')),
            ],
            options={
                'verbose_name': '基金管理人',
                'verbose_name_plural': '基金管理人',
                'db_table': 'sma_fund_advisor',
            },
        ),
    ]
