# Generated by Django 3.1.2 on 2020-12-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0040_fundadvisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(max_length=4, verbose_name='风险等级')),
                ('maturity', models.CharField(max_length=10, verbose_name='投资期限')),
                ('arr', models.CharField(max_length=10, verbose_name='目标收益')),
                ('volatility', models.CharField(max_length=20, verbose_name='目标风险')),
                ('fluidity', models.CharField(max_length=20, verbose_name='流动性要求')),
                ('age', models.IntegerField(max_length=3, verbose_name='年龄')),
                ('experience', models.CharField(max_length=20, verbose_name='投资经验')),
                ('plan', models.CharField(max_length=50, verbose_name='大额支出计划')),
                ('tolerance', models.CharField(max_length=20, verbose_name='回撤容忍度')),
                ('alter_limit', models.CharField(max_length=20, verbose_name='另类资产限制')),
                ('cross_border_limit', models.CharField(max_length=20, verbose_name='跨境投资限制')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investment.portfolio', to_field='port_code', verbose_name='所属组合')),
            ],
            options={
                'verbose_name': '客户评测主要信息',
                'verbose_name_plural': '客户评测主要信息',
                'db_table': 'sma_questionnaire_summary',
            },
        ),
    ]
