# Generated by Django 3.1.2 on 2020-12-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0041_clientq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientq',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
    ]
