# Generated by Django 3.1.2 on 2021-01-04 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0042_auto_20201224_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=20, verbose_name='手机')),
                ('mail', models.CharField(max_length=50, verbose_name='邮箱')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code', verbose_name='组合代码')),
            ],
            options={
                'verbose_name': '组合对应销售人员',
                'verbose_name_plural': '组合对应销售人员',
                'db_table': 'sma_sales',
            },
        ),
    ]
