# Generated by Django 3.1.5 on 2021-01-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0043_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreValuedNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='预估值日期')),
                ('value', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='预估净值')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code', verbose_name='组合代码')),
            ],
            options={
                'verbose_name': '组合每日预估值记录',
                'verbose_name_plural': '组合每日预估值记录',
                'db_table': 'sma_portfolio_pre_valuation',
            },
        ),
    ]
