# Generated by Django 3.1.5 on 2021-01-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0045_auto_20210106_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True, verbose_name='申购金额')),
                ('ransom_share', models.DecimalField(decimal_places=2, max_digits=18, null=True, verbose_name='赎回份额')),
                ('p_open_date', models.DateField(null=True, verbose_name='申购开放日')),
                ('r_open_date', models.DateField(null=True, verbose_name='赎回开放日')),
                ('p_confirm', models.IntegerField(choices=[(1, 'T+1'), (2, 'T+2'), (3, 'T+3'), (4, 'T+4')], null=True, verbose_name='赎回确认日')),
                ('r_confirm', models.IntegerField(choices=[(1, 'T+1'), (2, 'T+2'), (3, 'T+3'), (4, 'T+4')], null=True, verbose_name='赎回确认日')),
                ('complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code', verbose_name='组合代码')),
            ],
            options={
                'verbose_name': '组合客户申赎记录',
                'verbose_name_plural': '组合客户申赎记录',
                'db_table': 'sma_client_pr',
            },
        ),
    ]
