# Generated by Django 3.1.5 on 2021-01-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0046_clientpr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpr',
            name='complete',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='clientpr',
            name='p_confirm',
            field=models.IntegerField(blank=True, choices=[(1, 'T+1'), (2, 'T+2'), (3, 'T+3'), (4, 'T+4')], null=True, verbose_name='赎回确认日'),
        ),
        migrations.AlterField(
            model_name='clientpr',
            name='p_open_date',
            field=models.DateField(blank=True, null=True, verbose_name='申购开放日'),
        ),
        migrations.AlterField(
            model_name='clientpr',
            name='purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='申购金额'),
        ),
        migrations.AlterField(
            model_name='clientpr',
            name='r_confirm',
            field=models.IntegerField(blank=True, choices=[(1, 'T+1'), (2, 'T+2'), (3, 'T+3'), (4, 'T+4')], null=True, verbose_name='赎回确认日'),
        ),
        migrations.AlterField(
            model_name='clientpr',
            name='r_open_date',
            field=models.DateField(blank=True, null=True, verbose_name='赎回开放日'),
        ),
        migrations.AlterField(
            model_name='clientpr',
            name='ransom_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='赎回份额'),
        ),
    ]
