# Generated by Django 3.1.5 on 2021-01-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0047_auto_20210106_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('buyvalue', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='买入金额')),
                ('sellvalue', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='买入金额')),
                ('netvalue', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='买入金额')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.stock', verbose_name='证券代码')),
            ],
            options={
                'verbose_name': '股票资金流动',
                'verbose_name_plural': '股票资金流动',
                'db_table': 'sma_stock_capital_flow',
            },
        ),
    ]
