# Generated by Django 3.1.5 on 2021-01-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0049_portfolioassetallocate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioassetallocate',
            name='alter',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='quanyi'),
        ),
        migrations.AlterField(
            model_name='portfolioassetallocate',
            name='equity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='quanyi'),
        ),
        migrations.AlterField(
            model_name='portfolioassetallocate',
            name='fix_income',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='gushou'),
        ),
        migrations.AlterField(
            model_name='portfolioassetallocate',
            name='money',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='huobi'),
        ),
    ]
