# Generated by Django 3.1.5 on 2021-01-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0050_auto_20210125_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundassociate',
            name='define',
            field=models.IntegerField(default=21, verbose_name='codedefine'),
            preserve_default=False,
        ),
    ]
