# Generated by Django 3.1.5 on 2021-02-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0053_fundposestimate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundposestimate',
            name='secucode',
        ),
    ]
