# Generated by Django 3.1.5 on 2021-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0055_auto_20210219_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioassetallocate',
            name='other',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='其他'),
        ),
    ]
