# Generated by Django 3.1.5 on 2021-02-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0056_portfolioassetallocate_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.funds', verbose_name='基金代码')),
            ],
            options={
                'verbose_name': '基金备投池',
                'verbose_name_plural': '基金备投池',
                'db_table': 'sma_observe_pool',
            },
        ),
    ]
