# Generated by Django 3.1.5 on 2021-03-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0057_observepool'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='category',
            field=models.CharField(default='开放式基金', max_length=20, verbose_name='证券类型'),
        ),
    ]
