# Generated by Django 3.1.5 on 2021-03-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0058_holding_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsYX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secucode', models.CharField(blank=True, max_length=12, null=True, verbose_name='证券代码')),
                ('operation', models.CharField(max_length=30, verbose_name='业务类型')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='确认金额')),
                ('shares', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='确认份额')),
                ('fee', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='费用')),
                ('apply', models.DateField(verbose_name='申请时间')),
                ('confirm', models.DateField(verbose_name='确认时间')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '组合交易流水-宜信普泽',
                'verbose_name_plural': '组合交易流水-宜信普泽',
                'db_table': 'sma_transactions_yx',
                'get_latest_by': ['confirm'],
            },
        ),
    ]
