# Generated by Django 3.1.5 on 2021-03-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0060_holdingyx'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingyx',
            name='shares_change',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='份额变化'),
        ),
        migrations.AlterField(
            model_name='holdingyx',
            name='shares',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='累计份额'),
        ),
    ]
