# Generated by Django 3.2.3 on 2021-05-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0062_auto_20210527_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closeprice', models.FloatField(verbose_name='收盘价')),
                ('prevcloseprice', models.FloatField(verbose_name='昨收')),
                ('date', models.DateField()),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.funds', verbose_name='基金代码')),
            ],
            options={
                'verbose_name': '基金场内收盘价',
                'verbose_name_plural': '基金场内收盘价',
                'db_table': 'sma_fund_quote',
            },
        ),
    ]
