# Generated by Django 3.2.3 on 2021-06-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0063_fundquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceexpanded',
            name='interest_pay',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='应付利息税'),
        ),
        migrations.CreateModel(
            name='InterestTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secucode', models.CharField(max_length=12, verbose_name='基金代码')),
                ('tax', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='当月累计利息税')),
                ('date', models.DateField(verbose_name='业务日期')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '组合场内交易基金利息税',
                'verbose_name_plural': '组合场内交易基金利息税',
                'db_table': 'sma_interest_tax',
                'get_latest_by': 'date',
            },
        ),
    ]
