# Generated by Django 3.2.3 on 2021-06-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0064_auto_20210602_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailfee',
            name='interest_tax',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='应付利息税'),
        ),
    ]
