# Generated by Django 3.2.4 on 2021-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0065_detailfee_interest_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secucode', models.CharField(max_length=20, verbose_name='指数代码')),
                ('secuabbr', models.CharField(max_length=50, verbose_name='指数名称')),
                ('date', models.DateField(verbose_name='交易日')),
                ('nevalue', models.FloatField(verbose_name='流入金额')),
                ('ma3', models.FloatField(verbose_name='三日均值')),
                ('ma5', models.FloatField(verbose_name='三日均值')),
                ('ma10', models.FloatField(verbose_name='三日均值')),
                ('sigma5', models.FloatField(verbose_name='五日标准差')),
                ('ma5_high', models.FloatField(verbose_name='上沿')),
                ('ma5_low', models.FloatField(verbose_name='下沿')),
            ],
            options={
                'verbose_name': '行业资金流向',
                'verbose_name_plural': '行业资金流向',
                'db_table': 'sma_industry_capital_flow',
                'get_latest_by': 'date',
            },
        ),
    ]
