# Generated by Django 3.2.4 on 2021-06-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0066_industrycf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industrycf',
            old_name='nevalue',
            new_name='netvalue',
        ),
    ]
