# Generated by Django 3.2.4 on 2021-06-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0067_rename_nevalue_industrycf_netvalue'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='industrycf',
            index_together={('secucode', 'date')},
        ),
    ]
