# Generated by Django 3.2.4 on 2021-06-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0070_auto_20210624_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrealtimeprice',
            name='id',
        ),
        migrations.AlterField(
            model_name='stockrealtimeprice',
            name='secucode',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='股票代码'),
        ),
    ]
