# Generated by Django 3.2.4 on 2021-06-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0071_auto_20210624_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrealtimeprice',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockrealtimeprice',
            name='secucode',
            field=models.CharField(max_length=12, verbose_name='股票代码'),
        ),
    ]
