# Generated by Django 3.2.4 on 2021-06-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0072_auto_20210624_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockRealtimePrice',
        ),
    ]
