# Generated by Django 3.2.5 on 2021-08-05 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0074_stockrealtimeprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('secucode', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='证券代码')),
                ('secuname', models.CharField(max_length=50, verbose_name='证券简称')),
                ('category', models.CharField(max_length=20, verbose_name='证券类别')),
                ('category_code', models.CharField(default='100000', max_length=20, verbose_name='类别代码')),
            ],
            options={
                'verbose_name': '5.5 证券主表(估值表)',
                'verbose_name_plural': '5.5 证券主表(估值表)',
                'db_table': 'sma_security',
                'unique_together': {('secucode', 'category')},
            },
        ),
        migrations.AlterModelOptions(
            name='balance',
            options={'get_latest_by': ('date',), 'verbose_name': '2.1 组合资产负债', 'verbose_name_plural': '2.1 组合资产负债'},
        ),
        migrations.AlterModelOptions(
            name='balanceexpanded',
            options={'get_latest_by': ('date',), 'verbose_name': '2.2 组合应收应付表', 'verbose_name_plural': '2.2 组合应收应付表'},
        ),
        migrations.AlterModelOptions(
            name='clientpr',
            options={'verbose_name': '5.1 组合客户申赎记录', 'verbose_name_plural': '5.1 组合客户申赎记录'},
        ),
        migrations.AlterModelOptions(
            name='detailfee',
            options={'get_latest_by': 'date', 'verbose_name': '4.3 组合费用提取明细', 'verbose_name_plural': '4.3 组合费用提取明细'},
        ),
        migrations.AlterModelOptions(
            name='holding',
            options={'get_latest_by': 'date', 'verbose_name': '4.1 组合持基明细', 'verbose_name_plural': '4.1 组合持基明细'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'get_latest_by': 'date', 'verbose_name': '3.1 组合损益表', 'verbose_name_plural': '3.1 组合损益表'},
        ),
        migrations.AlterModelOptions(
            name='incomeasset',
            options={'get_latest_by': 'date', 'verbose_name': '3.2 组合资产损益表', 'verbose_name_plural': '3.2 组合资产损益表'},
        ),
        migrations.AlterModelOptions(
            name='interesttax',
            options={'get_latest_by': 'date', 'verbose_name': '4.4 组合场内交易基金利息税', 'verbose_name_plural': '4.4 组合场内交易基金利息税'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': '1. 组合基础信息', 'verbose_name_plural': '1. 组合基础信息'},
        ),
        migrations.AlterModelOptions(
            name='portfolioassetallocate',
            options={'get_latest_by': 'date', 'verbose_name': '4.9 组合资产配置', 'verbose_name_plural': '4.9 组合资产配置'},
        ),
        migrations.AlterModelOptions(
            name='portfoliobrinson',
            options={'verbose_name': '4.7 组合Brinson', 'verbose_name_plural': '4.7 组合Brinson'},
        ),
        migrations.AlterModelOptions(
            name='portfoliostyle',
            options={'verbose_name': '4.6 组合风格', 'verbose_name_plural': '4.6 组合风格'},
        ),
        migrations.AlterModelOptions(
            name='prevaluednav',
            options={'verbose_name': '4.8 组合每日预估值记录', 'verbose_name_plural': '4.8 组合每日预估值记录'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': '1.2 组合对应销售人员', 'verbose_name_plural': '1.2 组合对应销售人员'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'get_latest_by': ['date'], 'verbose_name': '4.2 组合交易流水', 'verbose_name_plural': '4.2 组合交易流水'},
        ),
        migrations.AlterModelOptions(
            name='valuationbenchmark',
            options={'get_latest_by': 'date', 'verbose_name': '4.5 组合基准净值表', 'verbose_name_plural': '4.5 组合基准净值表'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='valid',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='settlemented',
            field=models.IntegerField(choices=[(0, '是'), (1, '否')], default=1, verbose_name='是否已清算'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='t_n',
            field=models.IntegerField(default=1, verbose_name='估值频率'),
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='业务日期')),
                ('auto_date', models.DateField(default=django.utils.timezone.now, verbose_name='操作日期')),
                ('price', models.FloatField(verbose_name='前收盘价')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.security')),
            ],
            options={
                'verbose_name': '5.6 证券行情数据(估值表)',
                'verbose_name_plural': '5.6 证券行情数据(估值表)',
                'db_table': 'sma_security_quote',
            },
        ),
    ]
