# Generated by Django 3.2.5 on 2021-08-30 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0075_auto_20210805_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='port_type',
            field=models.IntegerField(choices=[(1, '现金型'), (2, '固收型'), (3, '平衡型'), (4, '成长型'), (5, '权益型'), (6, 'CTA')], default=3, verbose_name='组合类型'),
        ),
        migrations.CreateModel(
            name='StockDailyQuoteHK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closeprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收盘价')),
                ('prevcloseprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收盘价')),
                ('date', models.DateField(verbose_name='交易日')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.stock', verbose_name='股票代码')),
            ],
            options={
                'verbose_name': '股票日行情',
                'verbose_name_plural': '股票日行情',
                'db_table': 'sma_stock_daily_quote_hk',
                'unique_together': {('secucode', 'date')},
            },
        ),
    ]
