# Generated by Django 3.2.8 on 2021-10-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0076_auto_20210830_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnYield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secucode', models.CharField(blank=True, max_length=12, null=True, verbose_name='证券代码')),
                ('date', models.DateField(verbose_name='更新日期')),
                ('buy_at', models.DateField(verbose_name='买入日期')),
                ('sell_at', models.DateField(verbose_name='卖出日期')),
                ('ret_yield', models.FloatField(default=0, verbose_name='持有期收益率')),
                ('annualized', models.FloatField(default=0, verbose_name='持有期年化收益率')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '组合持基区间收益',
                'verbose_name_plural': '组合持基区间收益',
                'db_table': 'sma_income_return_yield',
                'get_latest_by': 'date',
            },
        ),
    ]
