# Generated by Django 3.2.8 on 2021-10-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0077_returnyield'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnyield',
            name='buy_price',
            field=models.FloatField(default=1, verbose_name='买入价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnyield',
            name='deal_value',
            field=models.FloatField(default=1, verbose_name='交易份额'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnyield',
            name='sell_price',
            field=models.FloatField(default=1, verbose_name='卖出价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityprice',
            name='o32',
            field=models.IntegerField(default=1, verbose_name='组合O32代码'),
            preserve_default=False,
        ),
    ]
