# Generated by Django 3.2.8 on 2021-10-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0079_portfolioexpanded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioExpanded',
        ),
    ]
