# Generated by Django 3.2.8 on 2021-10-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0080_delete_portfolioexpanded'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioExpanded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o32', models.IntegerField(verbose_name='o32中基金编号')),
                ('valuation', models.CharField(max_length=50, verbose_name='估值表中基金名称')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investment.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '1.2 组合代码在O32和估值表中对应关系',
                'verbose_name_plural': '1.2 组合代码在O32和估值表中对应关系',
                'db_table': 'sma_portfolio_expanded',
            },
        ),
    ]
