# Generated by Django 3.2.8 on 2021-10-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0081_portfolioexpanded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnyield',
            name='sell_at',
            field=models.DateField(null=True, verbose_name='卖出日期'),
        ),
        migrations.AlterField(
            model_name='returnyield',
            name='sell_price',
            field=models.FloatField(null=True, verbose_name='卖出价格'),
        ),
    ]
