# Generated by Django 3.2.8 on 2021-10-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0082_auto_20211019_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important', models.CharField(blank=True, max_length=20, null=True, verbose_name='仓位')),
                ('style', models.CharField(blank=True, max_length=20, null=True, verbose_name='风格')),
                ('flag', models.CharField(blank=True, max_length=20, null=True, verbose_name='标签')),
                ('secucode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.funds')),
            ],
            options={
                'verbose_name': '基金池-基金风格及标签',
                'verbose_name_plural': '基金池-基金风格及标签',
                'db_table': 'sma_holding_important',
            },
        ),
    ]
