# Generated by Django 3.2.3 on 2021-05-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cta_fof', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='balanceexpanded',
            table='cta_balance_expanded',
        ),
    ]
