# Generated by Django 3.2.3 on 2021-05-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cta_fof', '0002_alter_balanceexpanded_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceexpanded',
            name='port_code',
        ),
        migrations.AlterIndexTogether(
            name='holding',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='holding',
            name='port_code',
        ),
        migrations.AlterIndexTogether(
            name='transactions',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='port_code',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='BalanceExpanded',
        ),
        migrations.DeleteModel(
            name='Holding',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
