# Generated by Django 3.2.3 on 2021-05-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cta_fof', '0004_balance_balanceexpanded_holding_portfolio_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioExpanded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o32_code', models.IntegerField(verbose_name='o32中基金编码')),
                ('valuation', models.CharField(max_length=100, verbose_name='估值表名称')),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cta_fof.portfolio', to_field='port_code')),
            ],
            options={
                'verbose_name': '组合对应O32和TA关联关系',
                'db_table': 'cta_portfolio_mapping',
            },
        ),
    ]
