# Generated by Django 3.2.3 on 2021-06-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta_fof', '0006_auto_20210527_1645'),
    ]

    operations = [
    ]
