# Generated by Django 3.2.3 on 2021-06-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta_fof', '0007_holding_trade_market'),
    ]

    operations = [
    ]
