# Generated by Django 3.2.4 on 2021-06-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cta_fof', '0007_auto_20210531_1318'),
        ('cta_fof', '0008_holding_trade_market'),
    ]

    operations = [
    ]
