# Generated by Django 3.2.4 on 2021-07-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta_fof', '0010_auto_20210624_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='security_deposit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='存出保证金'),
        ),
        migrations.AddField(
            model_name='balanceexpanded',
            name='interest_pay',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='应付利息税'),
        ),
    ]
